# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IICsmallBusiness' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IICsmallBusiness
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase'
  target 'IICsmallBusinessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IICsmallBusinessUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
